#
# TABLE STRUCTURE FOR: app_masukan
#

DROP TABLE IF EXISTS `app_masukan`;

CREATE TABLE `app_masukan` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) NOT NULL,
  `email` varchar(100) NOT NULL,
  `jenis_kel` enum('Laki-laki','Perempuan') NOT NULL,
  `no_telp` int(13) unsigned NOT NULL,
  `alamat` varchar(255) NOT NULL,
  `pesan` text NOT NULL,
  `waktu_diterima` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8;

INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (1, 'Faustino Bergstrom', 'chadd.greenholt@example.net', 'Perempuan', 4294967295, '507 Schamberger Mall Suite 416', 'Quia iusto eaque labore rerum illum velit aliquid. Dolorem consequatur occaecati non corporis quo et vel. Totam officia nostrum consequatur incidunt dolore tenetur blanditiis.', '2001-09-25 03:41:57');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (2, 'Mr. Rocky Boyle DVM', 'yolanda.schultz@example.org', 'Laki-laki', 570076, '210 Colton Square', 'Quidem illum consequatur delectus autem consequuntur ut eveniet. Omnis consequuntur molestias dolores debitis similique expedita. Dolor corrupti quam ipsam.', '2019-05-08 19:46:59');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (3, 'Benedict Ratke', 'haylie91@example.com', 'Perempuan', 0, '6161 Powlowski Place', 'In quis sint voluptatem molestias rerum expedita. Optio quis quia minima reiciendis veniam consequatur. Id qui praesentium dolorum ipsam.', '1983-09-26 05:31:18');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (4, 'Miss Kyra Hane DVM', 'kihn.wade@example.net', 'Perempuan', 0, '23886 Schumm Burgs', 'Voluptatum eaque fugit accusamus quia reiciendis eius qui. Voluptatum possimus dignissimos voluptas ut. Adipisci unde nihil est nihil quasi explicabo.', '1981-12-28 23:50:06');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (5, 'Bettie Morar', 'jules.ortiz@example.net', 'Perempuan', 1, '7761 Zoey Plains Apt. 426', 'Quibusdam illo ut esse saepe. Laborum excepturi aspernatur assumenda vitae et cumque quas.', '2013-07-20 10:23:11');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (6, 'Winfield Schowalter', 'gage.wilkinson@example.org', 'Perempuan', 24, '80348 Lehner Springs', 'Vero alias qui temporibus magnam quasi est. Quibusdam temporibus sed odio mollitia. Non tenetur perspiciatis accusantium dolorum.', '1986-05-24 21:53:21');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (7, 'Marquise Larson V', 'fabiola60@example.com', 'Laki-laki', 223990, '5633 Dorthy Greens Apt. 474', 'Blanditiis maxime dolores non sapiente. Optio velit quasi unde qui qui aspernatur. Et officiis corrupti quidem excepturi harum labore voluptatem. Rerum ullam porro quisquam aut aut qui temporibus.', '2007-10-06 09:40:27');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (8, 'Prof. Bartholome Swift MD', 'ena02@example.com', 'Perempuan', 1, '3532 Susan Bypass', 'Quia ab inventore est laudantium rerum occaecati. Corporis sint ea perferendis et non quas. Est eaque nemo molestias at.', '2002-06-17 14:23:23');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (9, 'Bertram McKenzie', 'nschimmel@example.com', 'Laki-laki', 13, '5935 Kris Lakes', 'Repellendus et qui quisquam nobis esse eaque saepe in. Unde ut consequatur magni et minima voluptatem. A explicabo aut omnis culpa culpa. Sunt incidunt qui et et et delectus.', '2002-02-14 21:48:03');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (10, 'Zena Schuppe', 'cleta.reichert@example.com', 'Laki-laki', 167965, '0072 Milton Field Apt. 257', 'Quam soluta pariatur quo necessitatibus voluptas. Itaque provident dicta enim rem incidunt velit consequatur.', '1989-06-22 22:04:39');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (11, 'Georgiana Durgan MD', 'gwalsh@example.com', 'Perempuan', 253708, '672 Johnathan Vista', 'Expedita ut tempora libero eveniet fugiat ea. Minima in rerum earum quia voluptatibus. Velit voluptatem perspiciatis vel ad. Ut ea alias dicta atque ut.', '2009-12-21 06:44:47');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (12, 'Brannon Sanford', 'frederique74@example.com', 'Laki-laki', 1, '5592 Joanne Mews Suite 147', 'Porro velit et voluptatem est natus. Consequatur beatae et expedita est. Dicta qui dolorem atque.', '1999-08-10 12:43:26');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (13, 'Ms. Natalia Von DVM', 'sean.halvorson@example.net', 'Perempuan', 591, '16069 Russ Freeway', 'Consequatur in explicabo rem quis deserunt. Vel asperiores est dolor ratione. Voluptatem aut recusandae dolorem exercitationem. Sit qui id voluptatem temporibus vel accusantium.', '1983-07-02 19:37:19');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (14, 'Jasen Hilll IV', 'gswift@example.net', 'Perempuan', 542, '72321 Dashawn Ford', 'Quidem harum eius cumque ea. Ipsam nostrum eos aut repellendus quidem recusandae. Qui maxime sit et in dolorum. Fuga architecto cum reiciendis autem blanditiis voluptas et.', '2007-05-30 02:14:01');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (15, 'Mrs. Danyka Lebsack', 'nicholaus.mosciski@example.com', 'Laki-laki', 1, '726 Bins Drive', 'Est qui veniam magni quis blanditiis quibusdam. Commodi eos qui rem quis qui molestias mollitia necessitatibus.', '1983-10-21 17:43:52');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (16, 'Taya Reichel', 'cristal49@example.net', 'Perempuan', 0, '634 Gulgowski Rapids', 'Laborum eum atque excepturi qui. Quia aut odit eligendi odit minima omnis consectetur. Culpa culpa vero quibusdam numquam distinctio nam numquam. Corrupti ab sint in.', '1971-08-06 21:18:02');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (17, 'Cielo Thompson', 'danika.satterfield@example.net', 'Perempuan', 1685007352, '78845 Hintz Drives Apt. 727', 'Quas et deserunt et et. Itaque et et quam quia. Ut eos error quia saepe aut. Blanditiis sed aliquam nemo soluta ea reiciendis veritatis.', '1992-11-18 02:17:50');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (18, 'Jacquelyn Koss', 'alphonso.o\'hara@example.org', 'Laki-laki', 965468, '3789 Senger Shore Apt. 778', 'Ut vel repellat eaque dolore. Et quidem velit eum quibusdam impedit similique. Non veritatis a soluta dolore sit. Quam voluptatem molestiae totam non possimus magnam.', '1982-11-17 05:06:11');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (19, 'Myrna Goyette III', 'bchristiansen@example.net', 'Laki-laki', 0, '21898 Haag Land Apt. 730', 'Eum quo vero cum rerum. Et qui doloremque corrupti. Doloremque dolorem quia aut atque quia officia.', '1994-06-08 06:35:45');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (20, 'Prof. Fermin Kshlerin II', 'rrunte@example.com', 'Laki-laki', 1, '1975 Roscoe Branch Suite 518', 'Sunt fuga maxime quo nam. Quo repellat illo impedit porro numquam vel quae illo. Maxime occaecati deserunt eius est. Voluptatibus reprehenderit nostrum aliquam voluptatem eum aliquam.', '1991-11-14 17:38:52');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (21, 'Josefina Bartell', 'harber.maximillian@example.com', 'Perempuan', 1, '31858 Hagenes Brooks Apt. 098', 'Ab voluptatibus distinctio consequatur et illum. Aperiam ea blanditiis ea. Molestiae sed blanditiis placeat aspernatur. Sint deleniti aliquid omnis sed eum dolores sed.', '1974-09-28 12:30:35');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (22, 'Florian Rodriguez', 'conroy.darrell@example.org', 'Laki-laki', 0, '94671 Ledner Circles', 'Perspiciatis rerum qui animi. Qui earum aut voluptatum quasi id corrupti. Consequatur voluptas non qui id.', '1996-02-20 00:02:37');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (23, 'Lacy Emmerich', 'dee.emmerich@example.com', 'Perempuan', 0, '0490 Jordi Keys Apt. 026', 'Qui ratione earum odit vero consectetur reiciendis sequi. Quia dolor dolore est cum. Sint incidunt nihil totam aperiam similique. Occaecati et non molestiae.', '1981-11-17 16:39:33');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (24, 'Immanuel O\'Conner', 'lynch.beverly@example.com', 'Laki-laki', 41, '32618 Hartmann Island', 'Dolorem cum deleniti cumque vero in tenetur aliquid. Soluta beatae atque numquam quae sint qui et. Molestiae perferendis non molestiae quo.', '1983-07-04 09:22:46');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (25, 'Hyman VonRueden', 'kbahringer@example.net', 'Laki-laki', 537108, '47833 Roy Falls Apt. 158', 'Molestiae sed quaerat assumenda totam. Quaerat culpa possimus quisquam voluptas harum asperiores. Earum maxime nihil odit voluptate quis. Cupiditate corrupti quisquam ullam fugiat.', '1998-07-31 16:33:13');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (26, 'Alford Corkery I', 'maybell14@example.com', 'Laki-laki', 0, '913 Emerson Port', 'Qui tempora sapiente ratione vero dolore veritatis. Nemo possimus quam voluptatem ipsum autem earum. Perferendis facere quisquam aut nihil vitae voluptas.', '1976-10-19 18:44:27');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (27, 'Pietro Buckridge', 'romaguera.kattie@example.net', 'Laki-laki', 331, '34986 Gislason Club Suite 332', 'Veniam nihil nam et atque. Atque eos nostrum quo. Quod quia id non.', '1982-03-02 14:29:43');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (28, 'Prof. Skylar Stamm Sr.', 'laura75@example.org', 'Perempuan', 189348, '42212 Hallie Freeway Apt. 762', 'Ipsam officia dicta est praesentium sit blanditiis. Quo et rerum quis totam velit numquam dolores. Iusto ea magnam minus deleniti magni et. Dolores aliquam adipisci reiciendis laboriosam aut.', '2016-08-01 05:17:47');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (29, 'Stuart Flatley', 'larson.janice@example.org', 'Laki-laki', 72956, '43571 O\'Conner Field Apt. 473', 'Velit exercitationem omnis rerum quidem. Autem optio et assumenda aut maxime nulla id. Placeat et molestiae culpa ut.', '1977-04-26 14:53:21');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (30, 'Ernestine Casper', 'lela.metz@example.net', 'Perempuan', 0, '85060 Wiegand Freeway', 'Rerum et praesentium laborum labore. Qui optio molestiae amet consectetur aliquam sit nam.', '1978-03-13 11:01:49');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (31, 'Fredrick Raynor', 'wrempel@example.net', 'Perempuan', 0, '13385 Talon Island', 'Odio ex doloremque enim perspiciatis eius occaecati. Aut culpa a fugit repudiandae. Omnis error nulla saepe quia. Officiis iure consectetur nemo sed.', '1975-05-09 16:33:37');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (32, 'Stella McClure MD', 'abigail.wyman@example.org', 'Perempuan', 4294967295, '91261 Leanna View', 'Qui eos ad non omnis doloremque maxime blanditiis nisi. Necessitatibus ab optio voluptates aut aut accusamus.', '2011-08-24 07:38:32');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (33, 'Dr. Lily Pacocha V', 'vanessa04@example.com', 'Laki-laki', 1, '20675 Vivien Mall Suite 041', 'Quidem veniam alias reiciendis. Mollitia quos consequatur dignissimos aliquam iure sit optio. Aspernatur vel et dignissimos ullam corrupti ut voluptas.', '1995-11-23 07:34:03');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (34, 'Edwin Blanda', 'halvorson.chester@example.net', 'Perempuan', 0, '131 Weissnat Club Suite 860', 'Tenetur voluptatem id veniam eius accusantium est cum placeat. Laborum quia est totam earum laboriosam voluptatem. Placeat quo doloribus et autem.', '1978-01-31 21:23:53');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (35, 'Dr. Parker Grimes IV', 'elwin.kulas@example.net', 'Laki-laki', 1, '635 Cierra Courts', 'Et laboriosam laboriosam dolorum dolorem nostrum ipsum excepturi. Itaque mollitia expedita ad voluptatem et. Eos molestiae enim porro dignissimos enim magni.', '2004-11-17 02:21:25');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (36, 'Alberto Hartmann', 'maiya15@example.com', 'Perempuan', 362525, '565 Anita Isle Suite 121', 'Ratione quis non eveniet fugit aut molestiae incidunt. Quisquam aut id voluptas voluptas aut. Impedit a animi voluptas nihil quod accusamus dolor nobis. Deleniti est hic laboriosam saepe dignissimos.', '1999-01-31 17:52:05');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (37, 'Miss Autumn Dicki DVM', 'pagac.myra@example.net', 'Laki-laki', 66227, '0677 Huel Bypass Apt. 379', 'Sed eaque inventore distinctio saepe. Dolores et eligendi a eos eos voluptatem aliquid. Est et molestiae enim odio quod. Asperiores voluptate placeat est.', '2011-11-21 21:00:28');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (38, 'Oleta O\'Keefe DVM', 'ddooley@example.net', 'Laki-laki', 414, '734 Matilda Mall', 'Exercitationem pariatur doloremque omnis quo ut. Sint labore temporibus aliquid consequuntur sed ut consequuntur eius. Molestiae harum cumque harum deserunt est nostrum officiis non.', '2002-10-10 20:00:52');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (39, 'Dr. Tony Flatley', 'alyson29@example.com', 'Laki-laki', 234756962, '9050 Reynolds Place Apt. 527', 'Autem aliquid placeat ipsum amet id cum nulla. Sint qui voluptatem est ad non. Libero dolores animi aspernatur commodi. Officia laborum et neque animi.', '1979-09-25 22:43:09');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (40, 'Garrison McClure', 'schultz.eileen@example.net', 'Laki-laki', 488643, '49291 Elijah Point Suite 071', 'Earum eum facilis ratione voluptatem. Hic rerum voluptatibus perspiciatis pariatur est similique. Odit ipsam incidunt dolorem eum et.', '2004-05-14 15:26:20');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (41, 'Esta Rath DVM', 'nitzsche.randal@example.net', 'Perempuan', 598735, '706 Wyman Mall', 'Consectetur est molestias eaque minus. Architecto qui a quidem dolorem. Eos facilis quibusdam ipsam debitis.', '1976-05-05 16:37:06');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (42, 'River Kilback', 'zieme.candace@example.com', 'Laki-laki', 0, '40708 Ruben Lane Suite 838', 'Atque laboriosam est enim architecto reprehenderit ab. Minima ab possimus aut. Distinctio voluptate modi neque mollitia harum.', '2017-11-07 16:17:08');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (43, 'Claude Boyle', 'ykozey@example.com', 'Perempuan', 1, '6566 O\'Connell Springs', 'Velit aperiam veniam molestias vitae molestias quibusdam. Mollitia nam quo in quia eligendi quisquam est. Iste odio porro eum excepturi.', '2017-05-10 12:12:08');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (44, 'Daphnee Bergnaum', 'herta66@example.com', 'Laki-laki', 1, '75682 Oberbrunner Avenue', 'Deserunt aut laudantium ipsam voluptatem at error nostrum. Ipsum aperiam laborum consequuntur. Dolorum autem non exercitationem error aliquam. Voluptates voluptas facere et ducimus debitis nesciunt.', '1980-07-10 11:46:13');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (45, 'Aisha Moen Jr.', 'hayden47@example.com', 'Laki-laki', 12, '9529 Dare Cliff', 'Vero et explicabo nobis suscipit ipsa. Voluptatem veritatis voluptatem corporis voluptatem eum ducimus placeat. Qui libero aut quo dolor ipsam. Sequi aut inventore et temporibus aut amet.', '1995-01-23 22:57:25');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (46, 'Ramona Spencer', 'rolfson.quentin@example.com', 'Laki-laki', 601, '5824 Graham Mission', 'Architecto consequuntur ea magni quis nihil inventore. Quia ut dolores ea qui fugit. Velit voluptatibus expedita eos enim inventore voluptas explicabo rem.', '2019-07-16 21:27:51');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (47, 'Kathlyn Aufderhar', 'jones.allison@example.com', 'Laki-laki', 1, '7037 Savannah Drive', 'Rerum earum voluptatibus accusamus modi dolor qui quos. Dolore repellendus beatae delectus voluptatum aspernatur quos et. Voluptas voluptate fugiat eos et. Cum eos deleniti provident aut.', '1974-08-20 12:49:54');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (48, 'Michael Orn', 'aron.borer@example.com', 'Laki-laki', 263, '731 Reese Brooks', 'Soluta aliquid voluptatem quo labore. Beatae a eum adipisci et.\nIpsa quia voluptates corporis sequi. Ea libero asperiores dicta inventore reprehenderit facere iusto.', '2005-08-04 04:52:07');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (49, 'Henderson Brown', 'mmann@example.net', 'Laki-laki', 1, '590 Carroll Islands Apt. 281', 'Omnis est nesciunt neque. Veritatis magni voluptates molestiae. Autem voluptatem ab inventore non voluptates et quis.', '1971-08-09 12:01:08');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (50, 'Fabian Schaefer', 'augustus.quigley@example.com', 'Perempuan', 1, '70978 Osinski Brooks Apt. 570', 'Laudantium maiores nostrum sunt commodi iusto. Aut blanditiis et ipsum ducimus sint doloribus occaecati. Asperiores similique quia nostrum quia quisquam ut in voluptatibus.', '2002-03-25 08:00:06');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (51, 'Elsie Schumm', 'marc67@example.net', 'Perempuan', 135452, '124 Conner Shoal', 'Odio qui et officiis. Sequi sit beatae omnis et culpa quia. Accusantium est magni eaque ipsam.', '1984-10-15 03:31:42');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (52, 'Alison Hane V', 'devante77@example.org', 'Laki-laki', 1, '531 Herzog Center Apt. 055', 'Sapiente ullam est dolorum vel. Ab nobis ratione est beatae voluptatem ipsa ipsa. Sint non sed et soluta necessitatibus voluptatibus eius blanditiis.', '2002-11-09 04:07:54');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (53, 'Rosario Morar', 'diego63@example.com', 'Laki-laki', 0, '5700 Hermann Ville', 'Quis a explicabo aperiam nemo. Consequatur architecto consequatur voluptatem et accusamus amet. Neque sunt est aliquid dicta incidunt quis.', '2014-06-27 17:19:48');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (54, 'Jacklyn Cremin', 'dach.hans@example.com', 'Laki-laki', 1, '2900 Alberta Villages Apt. 903', 'Ratione nisi et tenetur quia qui repudiandae culpa. Architecto molestiae impedit qui. Nesciunt quia error beatae sequi. Dolore aliquid a et voluptas ipsam a.', '1974-10-07 03:55:22');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (55, 'Mr. Justyn Gerhold DDS', 'eschaefer@example.com', 'Perempuan', 185, '39347 Jane Street', 'Quia ut porro minus. Animi cumque consequatur quis a occaecati.\nEx minus incidunt eaque ea consequatur. Et porro officiis ipsam. Sit eum quia magnam est et. Quam sed consequatur ut dolorem atque.', '2010-09-19 05:59:45');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (56, 'Kraig Crooks MD', 'murphy.lloyd@example.com', 'Perempuan', 822, '58280 Harvey Shoals Suite 917', 'Excepturi qui incidunt sint numquam. Facere nihil cumque alias enim. Itaque delectus rerum qui est.', '2010-04-14 20:18:41');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (57, 'Brianne Dickinson', 'treutel.josefina@example.net', 'Laki-laki', 4294967295, '8961 Jackie Spring', 'Qui sed provident ut alias rem. Beatae ducimus voluptatem autem cum id cum. Pariatur laudantium voluptas quod debitis.', '1972-11-10 06:28:08');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (58, 'Mr. Melany Baumbach', 'lizeth00@example.net', 'Perempuan', 331, '25267 Weimann Heights', 'Quia numquam maiores dicta nesciunt repellendus. Voluptatum inventore ut consequatur sed et. Quia vero dolorem voluptatem consequuntur. Illo aut dolores quis sed. Nam et beatae et libero ullam.', '1973-10-05 20:44:46');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (59, 'Eddie Terry', 'leopold.torphy@example.net', 'Perempuan', 37, '47752 Deron Mountain', 'Alias corrupti est voluptatem dolor enim. Omnis dolores voluptas accusamus incidunt assumenda nostrum iste. Dolorum cum autem et molestiae et.', '1993-02-28 11:06:44');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (60, 'Evie Stehr', 'abbott.kailee@example.com', 'Perempuan', 613150, '567 Sylvester Ports', 'Consectetur laborum aut veritatis et voluptas. Illum non fuga ex sed. Vel pariatur deserunt et. Est tempora quia qui assumenda.', '1984-04-27 13:38:22');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (61, 'Ephraim Monahan DVM', 'louie77@example.org', 'Laki-laki', 184928, '6417 Konopelski Mill', 'Consequatur nulla qui id et molestiae. Rerum sapiente eum repellendus explicabo eum. Earum veritatis est et ut voluptatum velit enim.', '1999-06-30 11:00:17');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (62, 'Gerardo Runolfsdottir', 'weissnat.emile@example.com', 'Perempuan', 363, '3796 Marvin Lights', 'Praesentium qui sed temporibus autem esse quos. Est magni non animi delectus qui. Dolores vero iusto non reiciendis nobis. Sed porro accusantium ab.', '1999-12-24 09:42:10');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (63, 'Madelynn Muller I', 'ted78@example.net', 'Perempuan', 25, '15266 Ashleigh Cove', 'Consequatur nostrum est cum iste autem sint quia. Inventore repudiandae error harum aperiam quis. Assumenda et consequatur debitis sit nisi.', '2014-12-04 22:39:44');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (64, 'Mr. Roy Grimes Sr.', 'zulauf.bria@example.com', 'Laki-laki', 1, '9943 Purdy Estates Suite 808', 'In excepturi enim sit corporis. Iste aut dignissimos doloribus at voluptatem vero cupiditate fugiat. Minima quo fugiat doloremque maiores est corporis dolore. Nihil iste voluptatum enim fuga nostrum.', '1971-07-20 02:33:40');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (65, 'Josiah Smitham', 'brendan89@example.com', 'Laki-laki', 0, '3642 Schamberger Extension Suite 586', 'Est aliquid debitis qui optio. Sunt totam doloremque sit error. Sint quae et officiis unde deleniti est aut cum.', '1992-03-02 20:15:24');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (66, 'Mr. Madisen Stanton', 'bayer.jermey@example.net', 'Perempuan', 0, '12874 Mina Courts', 'Quis corporis doloribus assumenda. Inventore ut omnis est.\nUllam ut occaecati nemo quia minima sunt. Consectetur quod velit inventore. Quo harum maxime mollitia sequi itaque impedit id.', '1999-09-17 06:25:51');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (67, 'Mary Luettgen', 'al74@example.com', 'Perempuan', 0, '752 Daniela Villages', 'Ullam aliquid eos dolor et rem. Inventore voluptates iure voluptatem est maiores ducimus aliquam. Quo quae voluptas fugit repellat corporis.', '2011-07-07 13:14:03');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (68, 'Prof. Garnet Hartmann', 'sflatley@example.org', 'Perempuan', 96, '337 Padberg Trace', 'Alias aut dolorem repellat ab. Illum corrupti sed enim distinctio et. Est quia ipsam odio eaque asperiores repellat. Sed est aut earum explicabo.', '1979-08-24 10:23:31');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (69, 'Abdullah Schowalter', 'fatima.medhurst@example.com', 'Perempuan', 877, '8471 Pollich Cape', 'Quis aut provident quae placeat nihil ut itaque. Autem blanditiis magnam aliquid et harum. Optio numquam nesciunt ut ipsam accusantium blanditiis.', '1997-10-06 19:03:20');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (70, 'Tamia Lemke', 'zane.botsford@example.com', 'Laki-laki', 1, '3470 Miracle Forge', 'Corporis minima ad vel enim a minima. Autem rerum sit eligendi et voluptatem consequatur numquam.', '1986-02-09 03:55:01');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (71, 'Deborah Bruen', 'wgoldner@example.org', 'Laki-laki', 666, '19370 Travis Run Suite 571', 'Velit vero odit sint facere. Quos facilis sint accusamus nihil quaerat sed mollitia. Alias dignissimos odio doloremque nulla temporibus et. Ut dolorum atque velit distinctio enim aperiam.', '1994-01-25 07:43:21');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (72, 'Frankie McLaughlin', 'kay.kuhic@example.org', 'Perempuan', 366401264, '35122 Elmo Islands Suite 879', 'Et saepe fugiat et. Ad totam et quo asperiores excepturi quo repellendus. Facere et veniam id magni.', '1987-05-08 04:17:20');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (73, 'Prof. Mittie Braun', 'gutmann.chandler@example.org', 'Perempuan', 915, '583 Adolf Crossing Suite 497', 'Et et velit enim vel voluptatem explicabo natus occaecati. Eligendi voluptatibus eligendi et iste. Sequi deleniti maxime expedita incidunt.', '2001-02-11 06:04:03');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (74, 'Luigi Weimann', 'max.gusikowski@example.net', 'Laki-laki', 506, '12721 Rau Brooks Suite 917', 'Quia repudiandae accusamus commodi magni repellat sunt similique. Doloribus illo qui dolorum dolor.', '1991-05-29 00:40:40');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (75, 'Minerva Hills DVM', 'utillman@example.org', 'Perempuan', 29, '369 Rosina Islands Apt. 663', 'Ut blanditiis eveniet dolorem qui. Qui totam repellendus esse ratione non. Voluptatem natus tenetur ex quis consequatur. Eos ducimus enim explicabo.', '1979-07-20 04:22:27');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (76, 'Henderson Rice', 'howell99@example.net', 'Perempuan', 549283, '36439 Lola Row Suite 134', 'Repudiandae praesentium voluptas at. Ab repellat quod itaque consectetur qui culpa delectus. Provident delectus officiis veritatis minus consequatur ex ducimus.', '1972-04-21 09:44:27');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (77, 'Tressie Gulgowski', 'donato.wuckert@example.net', 'Laki-laki', 76, '745 Milan Shoals Suite 566', 'Voluptatem alias harum dolores porro adipisci voluptas cum. Cum voluptate aut non. Ipsum rem magnam tempora in dolores rerum eius. Rem voluptas quis vel magni.', '2004-09-02 04:04:39');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (78, 'Camylle Spinka', 'caleigh27@example.com', 'Laki-laki', 0, '6142 Thompson Gardens Apt. 094', 'Facilis corporis nulla adipisci possimus veritatis. Vel ut architecto officia velit aut vero. Ut sit et ut eum. Dolores cupiditate et blanditiis quos et eligendi odit dolorem.', '2012-03-25 01:54:05');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (79, 'Jaycee Nitzsche', 'rod84@example.com', 'Perempuan', 735, '666 Jacobi Park Suite 817', 'Aut delectus omnis voluptatem sint quasi rem. Autem quibusdam officiis facilis nihil. Minima enim repudiandae suscipit non. Excepturi quasi maiores minus officiis eum cumque rem.', '1970-03-01 08:14:24');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (80, 'Columbus Kirlin', 'earlene63@example.net', 'Perempuan', 309, '73601 Catalina Dale', 'Eum non voluptas magnam est modi voluptatibus. Velit optio in fugit voluptas eligendi accusantium vero.', '1972-08-09 00:33:47');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (81, 'Roma Davis', 'tondricka@example.net', 'Laki-laki', 0, '229 Karlee Crest', 'Qui libero omnis magnam. Sint commodi quam nulla aut dolor blanditiis. Sed distinctio sit facilis animi. Eum quis aut sapiente quae saepe.', '1975-12-31 21:16:18');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (82, 'Helene Hermiston', 'aleuschke@example.com', 'Laki-laki', 236520, '6594 Garett Villages', 'Fugit quia sed aspernatur et odit qui. Aliquam pariatur rerum deserunt. Aut optio culpa esse dolorum velit vitae. Repellat perferendis ut numquam facere provident inventore unde.', '1989-08-14 18:52:32');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (83, 'Avis Bradtke', 'ulittle@example.com', 'Laki-laki', 0, '6527 Nitzsche Skyway', 'Quisquam earum sed ut est. Sunt ut dolores aliquid sit totam rerum. Aliquid dolor nam deserunt perspiciatis quae a. Ea recusandae explicabo provident blanditiis optio dolorum.', '1989-08-08 12:29:03');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (84, 'Mr. Toy Zieme', 'payton.kohler@example.net', 'Perempuan', 1, '13080 Josue Neck Suite 824', 'Ipsam accusamus illo omnis dolores deserunt sint alias ut. Voluptas excepturi commodi qui est dicta. Et architecto qui perspiciatis ratione. Nulla quae ea laudantium sequi.', '1997-06-22 02:49:41');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (85, 'George Veum II', 'huel.trudie@example.net', 'Perempuan', 22, '5969 Marvin Field', 'Qui ipsam eligendi saepe itaque accusantium quis. Molestiae facilis blanditiis sit soluta. Repellat qui consequatur et rem maiores dolores harum.', '2006-03-22 12:19:53');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (86, 'Miss Marilou Lindgren', 'adrienne10@example.org', 'Laki-laki', 1, '96666 Evert Loop', 'Quia omnis aliquam numquam. Saepe ut et quia. Illum blanditiis impedit deserunt.', '2010-07-27 04:01:26');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (87, 'Angel Bartell', 'vicenta.toy@example.org', 'Perempuan', 793784, '315 Queenie Port Suite 593', 'Porro alias natus et. Nihil nisi laborum debitis aspernatur sunt explicabo numquam. Totam animi odit dolorem ut aut nesciunt.', '1976-09-23 06:17:33');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (88, 'Jasen Willms MD', 'harris.philip@example.org', 'Laki-laki', 248689, '33383 Margarett Wells', 'Nam dolorum vero eum voluptates et dolores. Sit nam non blanditiis voluptatem molestias architecto. Aut facilis rerum velit et dolores facilis natus.', '1985-04-11 10:03:12');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (89, 'Jerod Hermann', 'qnikolaus@example.com', 'Laki-laki', 4294967295, '8596 Rowan Plain', 'Blanditiis placeat nobis aut. Natus sint repellendus dicta est. Explicabo molestias minus beatae aspernatur.', '1982-03-07 17:42:16');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (90, 'Mr. Llewellyn Swift', 'jerrell.jakubowski@example.com', 'Perempuan', 417052, '511 Lou Stravenue', 'Iure pariatur sint voluptatem qui voluptatem odio. Aliquam eum est est et quibusdam qui minima. Laboriosam voluptatem doloribus illo est ea.', '2007-03-02 01:20:17');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (91, 'Mr. Michel Moen', 'lveum@example.com', 'Perempuan', 4294967295, '16547 Swift Viaduct', 'Est sequi quasi in sunt qui. Nam qui tenetur eligendi accusamus perspiciatis laborum. Officia est occaecati dolorem.', '1975-08-24 02:22:48');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (92, 'Chesley Satterfield', 'libbie34@example.net', 'Laki-laki', 146, '9828 Beier Neck Apt. 582', 'Dolores omnis est est culpa eos. Quaerat labore occaecati non. Aut error totam doloribus libero.', '1987-10-01 08:31:58');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (93, 'Brayan Haley', 'dereck09@example.net', 'Perempuan', 4294967295, '875 Maggie Camp', 'Vero eveniet quod molestiae sapiente dicta. Officia quod necessitatibus impedit laudantium. Accusantium nostrum sit aut incidunt sint dolores tempora.', '1992-07-12 02:57:39');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (94, 'Amely Balistreri', 'torp.bell@example.com', 'Laki-laki', 0, '15351 Spinka Mission Suite 510', 'Non voluptatibus quis voluptas qui aperiam. Incidunt eos pariatur pariatur ut quam qui id. Aliquid autem voluptatem consequuntur impedit.', '2010-11-27 03:04:35');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (95, 'Alda Hane', 'sawayn.ellie@example.com', 'Perempuan', 308, '0125 Katherine Unions Suite 945', 'Quod reiciendis iusto quasi. Maxime vero dignissimos est alias ut ut magni est. Qui est officia reiciendis porro veniam. Illo aliquid tenetur sed voluptas.', '1970-03-23 18:06:00');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (96, 'Chaz Shields', 'gkunde@example.com', 'Perempuan', 1, '3575 Turcotte Village', 'Ab ipsam dolorem distinctio cum ut. Recusandae voluptatem nihil natus ipsum nihil nulla. Aut optio a quo sit cupiditate optio. Harum modi sit est non animi enim.', '1983-04-18 12:54:18');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (97, 'Adrianna Connelly', 'davon26@example.org', 'Perempuan', 534997, '2360 Duncan Court Apt. 484', 'Et in repudiandae quaerat eum dolores et unde. Quas perferendis illo dolores consequatur. Quis sit harum maxime maxime magni occaecati.', '2008-09-30 14:24:20');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (98, 'Mr. Ernesto Powlowski', 'tomasa.schultz@example.com', 'Perempuan', 832, '88718 Arch Parkway', 'Beatae quo excepturi pariatur. Doloribus incidunt adipisci et. Aut possimus libero rerum sapiente sit explicabo ea.', '1989-09-25 03:29:23');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (99, 'Destiny Deckow Jr.', 'jamison45@example.org', 'Perempuan', 1, '0962 Lueilwitz Mews', 'Sint tempora accusamus fuga voluptate. Voluptates doloribus eos voluptatibus excepturi et earum libero. Velit mollitia ducimus quidem facere non sequi. Ea asperiores quibusdam ut aliquam.', '1996-07-11 09:34:11');
INSERT INTO `app_masukan` (`id`, `nama`, `email`, `jenis_kel`, `no_telp`, `alamat`, `pesan`, `waktu_diterima`) VALUES (100, 'Chadrick Sauer', 'keebler.brannon@example.org', 'Perempuan', 4294967295, '4629 Hyatt Ports Apt. 794', 'Temporibus fugiat sed ut accusamus quis. Deserunt dolorum dolorem qui sint facilis. Quasi exercitationem vero rerum. Voluptatem neque nihil ullam ex.', '1999-07-18 23:38:31');


